#!/usr/bin/env python3
"""Local BM25 search for an LLM Wiki.

This script is generated by llm-wiki-bootstrap when BM25 search is enabled.
It uses only Python's standard library plus SQLite FTS5.

Keep this script's SQLite schema, EXPORT_FIELDS, and search output contract in
sync with the Data Model section generated in indexes/README.md.
"""

from __future__ import annotations

import argparse
import csv
import json
import re
import sqlite3
from collections.abc import Iterable, Sequence
from contextlib import closing
from dataclasses import dataclass
from pathlib import Path


ROOT = Path(__file__).resolve().parents[1]
WIKI_DIR = ROOT / "wiki"
INDEX_DIR = ROOT / "indexes"
EXPORT_DIR = ROOT / "exports"
DB_PATH = INDEX_DIR / "fts.sqlite"

SCHEMA_VERSION = "1"
DEFAULT_MAX_CHARS = 1800
DEFAULT_OVERLAP_CHARS = 200
DEFAULT_SNIPPET_CHARS = 360
DEFAULT_LIMIT = 10

EXPORT_FIELDS = (
    "chunk_id",
    "page_path",
    "title",
    "type",
    "heading_path",
    "ordinal",
    "sources",
    "tags",
    "updated",
    "text",
)

FENCED_CODE_RE = re.compile(r"```.*?```", re.DOTALL)
INLINE_CODE_RE = re.compile(r"`([^`]*)`")
IMAGE_RE = re.compile(r"!\[[^\]]*\]\([^)]+\)")
MARKDOWN_LINK_RE = re.compile(r"\[([^\]]+)\]\([^)]+\)")
WIKILINK_RE = re.compile(
    r"\[\[(?P<target>[^\]|#]+)(?:#[^\]|]+)?(?:\|(?P<alias>[^\]]+))?\]\]"
)
HTML_TAG_RE = re.compile(r"<[^>]+>")
HEADING_RE = re.compile(r"^(#{1,6})\s+(.+?)\s*$")
FTS_TOKEN_RE = re.compile(r"[^\W_][\w-]*", re.UNICODE)


@dataclass(frozen=True, slots=True)
class Page:
    path: str
    title: str
    page_type: str
    updated: str
    sources: str
    tags: str
    text: str


@dataclass(frozen=True, slots=True)
class Chunk:
    chunk_id: str
    page_path: str
    title: str
    page_type: str
    heading_path: str
    ordinal: int
    sources: str
    tags: str
    updated: str
    text: str


def connect() -> sqlite3.Connection:
    INDEX_DIR.mkdir(parents=True, exist_ok=True)
    return sqlite3.connect(DB_PATH)


def ensure_fts5() -> None:
    try:
        with sqlite3.connect(":memory:") as con:
            con.execute("CREATE VIRTUAL TABLE t USING fts5(x)")
            con.execute("INSERT INTO t(x) VALUES ('hello world')")
            con.execute("SELECT rowid FROM t WHERE t MATCH 'hello'")
    except sqlite3.Error as exc:
        raise SystemExit(f"SQLite FTS5 is not available: {exc}") from exc


def require_index() -> None:
    if not DB_PATH.exists():
        raise SystemExit("No BM25 index found. Run: python3 scripts/wiki_fts.py build")


def validate_chunk_options(max_chars: int, overlap_chars: int) -> None:
    if max_chars <= 0:
        raise SystemExit("--max-chars must be greater than zero")
    if overlap_chars < 0:
        raise SystemExit("--overlap-chars cannot be negative")
    if overlap_chars >= max_chars:
        raise SystemExit("--overlap-chars must be smaller than --max-chars")


def parse_frontmatter(text: str) -> tuple[dict[str, str], str]:
    if not text.startswith("---\n"):
        return {}, text

    end = text.find("\n---\n", 4)
    if end == -1:
        return {}, text

    raw_frontmatter = text[4:end]
    body = text[end + 5 :]
    data: dict[str, str] = {}

    for line in raw_frontmatter.splitlines():
        if ":" not in line:
            continue
        key, value = line.split(":", 1)
        data[key.strip()] = value.strip().strip("\"'")

    return data, body


def first_heading(text: str) -> str:
    for line in text.splitlines():
        if line.startswith("# "):
            return line[2:].strip()
    return ""


def wikilink_label(match: re.Match[str]) -> str:
    return match.group("alias") or match.group("target")


def strip_markdown(text: str) -> str:
    text = FENCED_CODE_RE.sub(" ", text)
    text = INLINE_CODE_RE.sub(r"\1", text)
    text = IMAGE_RE.sub(" ", text)
    text = MARKDOWN_LINK_RE.sub(r"\1", text)
    text = WIKILINK_RE.sub(wikilink_label, text)
    text = HTML_TAG_RE.sub(" ", text)
    return re.sub(r"\s+", " ", text).strip()


def read_pages() -> list[Page]:
    if not WIKI_DIR.exists():
        raise SystemExit(f"No wiki directory found at {WIKI_DIR}")

    pages: list[Page] = []
    for path in sorted(WIKI_DIR.rglob("*.md")):
        raw = path.read_text(encoding="utf-8")
        frontmatter, body = parse_frontmatter(raw)
        title = (
            frontmatter.get("title")
            or first_heading(body)
            or path.stem.replace("-", " ").title()
        )
        pages.append(
            Page(
                path=path.relative_to(ROOT).as_posix(),
                title=title,
                page_type=frontmatter.get("type", ""),
                updated=frontmatter.get("updated", ""),
                sources=frontmatter.get("sources", "[]"),
                tags=frontmatter.get("tags", "[]"),
                text=body,
            )
        )
    return pages


def iter_text_chunks(
    raw_text: str, *, max_chars: int, overlap_chars: int
) -> Iterable[str]:
    clean = strip_markdown(raw_text)
    if not clean:
        return

    start = 0
    while start < len(clean):
        end = min(start + max_chars, len(clean))
        chunk = clean[start:end].strip()
        if chunk:
            yield chunk
        if end >= len(clean):
            break
        start = max(end - overlap_chars, start + 1)


def split_chunks(
    page: Page,
    *,
    max_chars: int = DEFAULT_MAX_CHARS,
    overlap_chars: int = DEFAULT_OVERLAP_CHARS,
) -> Iterable[Chunk]:
    headings: list[str] = []
    section_heading = page.title
    section_lines: list[str] = []
    ordinal = 0

    def flush_section(heading_path: str, lines: Sequence[str]) -> Iterable[Chunk]:
        nonlocal ordinal
        raw_text = "\n".join(lines).strip()
        for text in iter_text_chunks(
            raw_text, max_chars=max_chars, overlap_chars=overlap_chars
        ):
            ordinal += 1
            yield Chunk(
                chunk_id=f"{page.path}#{ordinal}",
                page_path=page.path,
                title=page.title,
                page_type=page.page_type,
                heading_path=heading_path,
                ordinal=ordinal,
                sources=page.sources,
                tags=page.tags,
                updated=page.updated,
                text=text,
            )

    for line in page.text.splitlines():
        match = HEADING_RE.match(line)
        if match:
            yield from flush_section(section_heading, section_lines)
            section_lines = []

            level = len(match.group(1))
            title = match.group(2).strip()
            headings[:] = headings[: level - 1]
            headings.append(title)
            section_heading = " > ".join(headings) if headings else page.title
        else:
            section_lines.append(line)

    yield from flush_section(section_heading, section_lines)


def init_schema(con: sqlite3.Connection) -> None:
    con.executescript(
        """
        DROP TABLE IF EXISTS pages;
        DROP TABLE IF EXISTS chunks;
        DROP TABLE IF EXISTS metadata;
        DROP TABLE IF EXISTS chunks_fts;

        CREATE TABLE pages (
            page_path TEXT PRIMARY KEY,
            title TEXT NOT NULL,
            type TEXT NOT NULL,
            updated TEXT NOT NULL,
            sources TEXT NOT NULL,
            tags TEXT NOT NULL,
            mtime REAL NOT NULL
        );

        CREATE TABLE chunks (
            chunk_id TEXT PRIMARY KEY,
            page_path TEXT NOT NULL,
            title TEXT NOT NULL,
            type TEXT NOT NULL,
            heading_path TEXT NOT NULL,
            ordinal INTEGER NOT NULL,
            sources TEXT NOT NULL,
            tags TEXT NOT NULL,
            updated TEXT NOT NULL,
            text TEXT NOT NULL
        );

        CREATE INDEX chunks_page_path_idx ON chunks(page_path);

        CREATE VIRTUAL TABLE chunks_fts USING fts5(
            chunk_id UNINDEXED,
            title,
            page_path UNINDEXED,
            heading_path,
            text
        );

        CREATE TABLE metadata (
            key TEXT PRIMARY KEY,
            value TEXT NOT NULL
        );
        """
    )


def insert_page(con: sqlite3.Connection, page: Page) -> None:
    mtime = (ROOT / page.path).stat().st_mtime
    con.execute(
        "INSERT INTO pages VALUES (?, ?, ?, ?, ?, ?, ?)",
        (
            page.path,
            page.title,
            page.page_type,
            page.updated,
            page.sources,
            page.tags,
            mtime,
        ),
    )


def insert_chunk(con: sqlite3.Connection, chunk: Chunk, rowid: int) -> None:
    con.execute(
        "INSERT INTO chunks VALUES (?, ?, ?, ?, ?, ?, ?, ?, ?, ?)",
        (
            chunk.chunk_id,
            chunk.page_path,
            chunk.title,
            chunk.page_type,
            chunk.heading_path,
            chunk.ordinal,
            chunk.sources,
            chunk.tags,
            chunk.updated,
            chunk.text,
        ),
    )
    con.execute(
        """
        INSERT INTO chunks_fts
          (rowid, chunk_id, title, page_path, heading_path, text)
        VALUES (?, ?, ?, ?, ?, ?)
        """,
        (
            rowid,
            chunk.chunk_id,
            chunk.title,
            chunk.page_path,
            chunk.heading_path,
            chunk.text,
        ),
    )


def command_build(args: argparse.Namespace) -> None:
    validate_chunk_options(args.max_chars, args.overlap_chars)
    ensure_fts5()

    pages = read_pages()
    chunk_count = 0

    with closing(connect()) as con:
        init_schema(con)
        for page in pages:
            insert_page(con, page)
            for chunk in split_chunks(
                page, max_chars=args.max_chars, overlap_chars=args.overlap_chars
            ):
                chunk_count += 1
                insert_chunk(con, chunk, chunk_count)

        con.execute("INSERT INTO metadata VALUES ('built_at', datetime('now'))")
        con.executemany(
            "INSERT INTO metadata VALUES (?, ?)",
            (
                ("schema_version", SCHEMA_VERSION),
                ("root", str(ROOT)),
                ("page_count", str(len(pages))),
                ("chunk_count", str(chunk_count)),
            ),
        )
        con.commit()

    print(f"Built {DB_PATH} with {len(pages)} pages and {chunk_count} chunks.")


def command_rebuild(args: argparse.Namespace) -> None:
    if DB_PATH.exists():
        DB_PATH.unlink()
    command_build(args)


def quote_fts_token(token: str) -> str:
    return '"' + token.replace('"', '""') + '"'


def make_match_query(query: str) -> str:
    tokens = [token for token in FTS_TOKEN_RE.findall(query) if token.strip()]
    if tokens:
        return " OR ".join(quote_fts_token(token) for token in tokens)

    stripped = query.strip()
    if not stripped:
        raise SystemExit("Search query cannot be empty")
    return quote_fts_token(stripped)


def collapse_whitespace(text: str) -> str:
    return re.sub(r"\s+", " ", text).strip()


def command_search(args: argparse.Namespace) -> None:
    require_index()
    match_query = make_match_query(args.query)

    try:
        with closing(connect()) as con:
            rows = con.execute(
                """
                SELECT
                  chunks_fts.chunk_id,
                  chunks_fts.page_path,
                  chunks_fts.title,
                  chunks_fts.heading_path,
                  snippets.text,
                  bm25(chunks_fts) AS score
                FROM chunks_fts
                JOIN chunks AS snippets ON snippets.chunk_id = chunks_fts.chunk_id
                WHERE chunks_fts MATCH ?
                ORDER BY score
                LIMIT ?
                """,
                (match_query, args.limit),
            ).fetchall()
    except sqlite3.Error as exc:
        raise SystemExit(f"Search failed: {exc}") from exc

    if not rows:
        print("No matches.")
        return

    for index, row in enumerate(rows, 1):
        chunk_id, page_path, title, heading_path, text, score = row
        snippet = collapse_whitespace(text)[: args.snippet_chars]
        print(f"{index}. {title} [{page_path}]")
        print(f"   heading: {heading_path}")
        print(f"   chunk: {chunk_id} score: {score:.4f}")
        print(f"   {snippet}")


def default_export_path(fmt: str) -> Path:
    suffix = {"jsonl": "jsonl", "csv": "csv", "markdown": "md"}[fmt]
    return EXPORT_DIR / f"bm25-chunks.{suffix}"


def chunk_rows() -> list[tuple[object, ...]]:
    require_index()
    with closing(connect()) as con:
        return con.execute(
            f"""
            SELECT {", ".join(EXPORT_FIELDS)}
            FROM chunks
            ORDER BY page_path, ordinal
            """
        ).fetchall()


def command_export(args: argparse.Namespace) -> None:
    rows = chunk_rows()
    output = Path(args.out) if args.out else default_export_path(args.format)
    output.parent.mkdir(parents=True, exist_ok=True)

    if args.format == "jsonl":
        with output.open("w", encoding="utf-8") as file:
            for row in rows:
                file.write(json.dumps(dict(zip(EXPORT_FIELDS, row)), ensure_ascii=False))
                file.write("\n")
    elif args.format == "csv":
        with output.open("w", encoding="utf-8", newline="") as file:
            writer = csv.writer(file)
            writer.writerow(EXPORT_FIELDS)
            writer.writerows(rows)
    elif args.format == "markdown":
        with output.open("w", encoding="utf-8") as file:
            file.write("# BM25 Index Export\n\n")
            file.write(f"- Chunks: {len(rows)}\n")
            file.write(f"- Database: `{DB_PATH.relative_to(ROOT)}`\n\n")
            for index, row in enumerate(rows):
                item = dict(zip(EXPORT_FIELDS, row))
                file.write(f"## {item['title']} - {item['chunk_id']}\n\n")
                file.write(f"- Path: `{item['page_path']}`\n")
                file.write(f"- Heading: {item['heading_path']}\n")
                file.write(f"- Chunk: `{item['chunk_id']}`\n\n")
                file.write(f"{item['text'].rstrip()}\n")
                if index < len(rows) - 1:
                    file.write("\n")
    else:
        raise SystemExit(f"Unsupported export format: {args.format}")

    print(f"Exported {len(rows)} chunks to {output}")


def scalar(con: sqlite3.Connection, query: str) -> object | None:
    row = con.execute(query).fetchone()
    return row[0] if row else None


def newest_wiki_mtime() -> float:
    return max((path.stat().st_mtime for path in WIKI_DIR.rglob("*.md")), default=0.0)


def command_stats(_: argparse.Namespace) -> None:
    if not DB_PATH.exists():
        print("BM25 index: missing")
        return

    with closing(connect()) as con:
        page_count = scalar(con, "SELECT COUNT(*) FROM pages")
        chunk_count = scalar(con, "SELECT COUNT(*) FROM chunks")
        built_at = scalar(con, "SELECT value FROM metadata WHERE key = 'built_at'")

    print(f"BM25 index: {DB_PATH.relative_to(ROOT)}")
    print(f"Pages: {page_count}")
    print(f"Chunks: {chunk_count}")
    print(f"Built at UTC: {built_at or 'unknown'}")
    print(f"Fresh: {'yes' if DB_PATH.stat().st_mtime >= newest_wiki_mtime() else 'no'}")


def command_doctor(_: argparse.Namespace) -> None:
    ensure_fts5()
    print("SQLite FTS5 is available.")


def build_parser() -> argparse.ArgumentParser:
    parser = argparse.ArgumentParser(description="Local BM25 search for an LLM Wiki")
    subcommands = parser.add_subparsers(dest="command", required=True)

    subcommands.add_parser("doctor").set_defaults(func=command_doctor)

    build_parser_ = subcommands.add_parser("build")
    build_parser_.add_argument("--max-chars", type=int, default=DEFAULT_MAX_CHARS)
    build_parser_.add_argument("--overlap-chars", type=int, default=DEFAULT_OVERLAP_CHARS)
    build_parser_.set_defaults(func=command_build)

    rebuild_parser = subcommands.add_parser("rebuild")
    rebuild_parser.add_argument("--max-chars", type=int, default=DEFAULT_MAX_CHARS)
    rebuild_parser.add_argument("--overlap-chars", type=int, default=DEFAULT_OVERLAP_CHARS)
    rebuild_parser.set_defaults(func=command_rebuild)

    search_parser = subcommands.add_parser("search")
    search_parser.add_argument("query")
    search_parser.add_argument("--limit", type=int, default=DEFAULT_LIMIT)
    search_parser.add_argument("--snippet-chars", type=int, default=DEFAULT_SNIPPET_CHARS)
    search_parser.set_defaults(func=command_search)

    export_parser = subcommands.add_parser("export")
    export_parser.add_argument(
        "--format", choices=["jsonl", "csv", "markdown"], default="jsonl"
    )
    export_parser.add_argument("--out")
    export_parser.set_defaults(func=command_export)

    subcommands.add_parser("stats").set_defaults(func=command_stats)
    return parser


def main() -> int:
    parser = build_parser()
    args = parser.parse_args()
    args.func(args)
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
